services:
  - type: web
    name: your-service-name  # Replace with your desired service name
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:server
    autoDeploy: true