name: Deploy Dash App to GitHub Pages

on:
  push:
    branches: [ main ]  # Cambia 'main' por tu rama principal si es diferente
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'  # Elige la versión de Python que usas
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install dash pandas plotly gunicorn
    
    - name: Build Dash App
      run: |
        mkdir public
        python app.py  # Esto generará los archivos estáticos
    
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
        publish_branch: gh-pages
